services:
  yt-dlp-web:
    image: goldic/yt-dlp-web-fork
    container_name: yt-dlp-web-fork
    user: 1000:1000
    # environment:
    #   If you need to protect the site, set AUTH_SECRET, CREDENTIAL_USERNAME, CREDENTIAL_PASSWORD.
    #   AUTH_SECRET: "Random_string,_40+_characters_recommended"
    #   CREDENTIAL_USERNAME: "username"
    #   CREDENTIAL_PASSWORD: "password"
    volumes:
      - ~/Desktop/downloads:/downloads
      - ~/Desktop/cache:/cache
    ports:
      - 3000:3000
    restart: unless-stopped
